plugins:
  - serverless-api-gateway-throttling
  - serverless-associate-waf

service: sqsgateway

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    SQS_HTTP_URL:
      Ref: AsyncAPIQueue
    API_KEY_ARN:
      Ref: APIKeySecret
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:GetQueueUrl"
        - "sqs:SendMessage"
      Resource:
        - 'Fn::GetAtt': [AsyncAPIQueue, Arn]
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - Ref: APIKeySecret

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 1
  associateWaf:
    name: ${self:service}-${self:provider.stage}-WebACL
    version: V2

functions:
  submit:
    handler: handlers/push.post
    timeout: 30
    response:
      headers:
        Content-Type: "'application/json'"
    events:
      - http:
          path: submit
          method: POST
          cors: false

resources:
  - ${file(resources/sqs.yml)}
  - ${file(resources/secrets.yml)}
  - ${file(resources/waf.yml)}
